### ISSUE TITLE
Support for websites that want a username/password

### ISSUE THREAD

**Issue by Sciencentistguy** [Skallwar/suckit#87]
There should be command line options to supply a http username and password.

**Comment by Skallwar** [comment]
Yes, thanks for the report :+1:

**Comment by pjsier** [comment]
@Skallwar I'm interested in taking this on if it's available!

**Comment by Skallwar** [comment]
> @Skallwar I'm interested in taking this on if it's available!

Go ahead ;)

**Comment by pjsier** [comment]
@Skallwar from looking into this a bit, it looks like HTTP basic auth is already supported by `reqwest` if you supply the credentials in the URL itself like "https://username:password@example.com/". Is this still something you'd want to implement command line options for?

If so, from what I'm seeing we could either set default HTTP basic auth headers in the `client` field of `Downloader` which would require adding the `base64` crate as an explicit dependency (because `reqwest` only has a helper method for `RequestBuilder`), or we could add `username` and `password` fields to `Downloader` that are set either on each `URL` or on each request.

Let me know what you think the best approach is, thanks!

**Comment by Skallwar** [comment]
I suggest [basic_auth](https://docs.rs/reqwest/0.10.8/reqwest/struct.RequestBuilder.html#method.basic_auth) because we may encounter different domain with different username/password. This way before making a request, we could fetch in a data structure (maybe a hashtable) a username/password.

From the command line, we need to be able to specify triplets separated with a ``,`` (or something else) with domain/username/password.
Reading from a file the same data could be better at first

**Comment by CohenArthur** [comment]
Closed with #96
